name: NuGet Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --no-restore --configuration Release

    - name: Pack NuGet Package(s)
      run: dotnet pack ./src --no-restore --no-build --configuration Release --output ./nuget-packages

    - name: Upload Build Artifact(s)
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nuget-packages

    - name: Push NuGet Package(s)
      run: dotnet nuget push ./nuget-packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
